#ifndef AM43XX_IDK_EVM_SHELLCONF_H_
#define AM43XX_IDK_EVM_SHELLCONF_H_

#define CONFIG_SHELL_STACKSZ 4096

#define CONFIG_DYNMAIC_LIB_CONTENT \
    "/etc/libdl*.a\n"
    
#define CONFIG_JOEL_SCRIPT_CONTENT \
    "#! joel -t JOEL -p 110 -s 8192\n" \
    "mkdir /temp\n" \
    "mkdos /dev/ram0\n" \
    "mount -t dosfs /dev/ram0 /temp\n"

#define CONFIGURE_SHELL_COMMAND_XMODEM
#define CONFIGURE_SHELL_COMMAND_IRQ
#define CONFIGURE_SHELL_COMMAND_CLEAR
#define CONFIGURE_SHELL_COMMANDS_INIT
#define CONFIGURE_SHELL_COMMANDS_ALL

#if defined(__rtems_libbsd__)
//#define CONFIGURE_BSD_SHELL_COMMAND_HOSTNAME
//#define CONFIGURE_BSD_SHELL_COMMAND_ARP
//#define CONFIGURE_BSD_SHELL_COMMAND_DHCPCD

#define CONFIGURE_BSD_SHELL_COMMAND_IFCONFIG
//#define CONFIGURE_BSD_SHELL_COMMAND_NETSTAT
//#define CONFIGURE_BSD_SHELL_COMMAND_NVMECONTROL
//#define CONFIGURE_BSD_SHELL_COMMAND_OPENSSL
//#define CONFIGURE_BSD_SHELL_COMMAND_PFCTL
#define CONFIGURE_BSD_SHELL_COMMAND_PING
//#define CONFIGURE_BSD_SHELL_COMMAND_RACOON
#define CONFIGURE_BSD_SHELL_COMMAND_ROUTE
//#define CONFIGURE_BSD_SHELL_COMMAND_SETKEY
//#define CONFIGURE_BSD_SHELL_COMMAND_STTY
#define CONFIGURE_BSD_SHELL_COMMAND_SYSCTL
//#define CONFIGURE_BSD_SHELL_COMMAND_TCPDUMP
//#define CONFIGURE_BSD_SHELL_COMMAND_VMSTAT
//#define CONFIGURE_BSD_SHELL_COMMAND_WLANSTATS
// #define CONFIGURE_BSD_SHELL_COMMAND_WPA_SUPPLICANT
// #define CONFIGURE_BSD_SHELL_COMMAND_WPA_SUPPLICANT_FORK
#endif /* __rtems_libbsd__ */
#endif /* AM43XX_IDK_EVM_SHELLCONF_H_ */
